Repository KushalZambare/PDFchatbot, pull requests merged in 2025-02, with the labels that each got.

#35 [FIX] Fixed UI, added OCR for scanned text and adding dark mode toggle button which is not visible#34 (Issue no. 34)
  Chatbot.ipynb
  app.py
Labels: acwoc, hard

#36 Add WebSocket Listener with Thread-Safe Queue for Real-Time Annotations #32 (Issue no.32)
  README.md
  app.py
  ws_server.py
Labels: acwoc, hard

#37 Integrate AI-Powered Summarization for PDF Content #33 (Issue no. 33)
  .streamlit/secrets.toml
  app.py
Labels: acwoc, medium

#41 [FEATURE] Add Real-Time Collaboration Enhancements (Chat, User Auth, and Revision History) #40 (Issue no. 40)
  app.py
Labels: acwoc, hard

#42 Improving and adding Audio Feature (Text-to-Speech Integration)
  app.py
  requirements.txt
Labels: acwoc, medium

#46 feat: Add PDF to Quiz Generation Feature #45 (Issue no. 45)
  app.py
Labels: enhancement, acwoc, hard

#48 feat: Add user-selectable themes to enhance UI customization
  app.py
Labels: acwoc, medium

#50 Add Semantic Search Feature and updated readme file.
  README.md
  app.py
Labels: acwoc, hard
