Repository KushalZambare/PDFchatbot, pull requests merged in 2025-01, with the labels that each got.

#2 Update README.md
  README.md
Labels: enhancement, acwoc, easy

#4 added: new features added according to issue #3
  Chatbot.ipynb
Labels: acwoc, medium

#6 Added GUI for PDF interaction, including upload and search functionality. #5 (issue no.5)
  Chatbot.ipynb
  README.md
Labels: acwoc, hard

#8 Advancement Of pdf chatbot
  RAG.py
  README copy.md
  requirements.txt
Labels: acwoc, hard

#12 Enhance PDF Chatbot with Modern GUI and Theme Toggle
  Chatbot.ipynb
Labels: acwoc, medium

#14 Conflict resolved
  Chatbot.ipynb
Labels: acwoc, medium

#16 Update README.md
  README.md
Labels: acwoc, easy

#18 Added Save Search Results feature & enhanced GUI buttons #17 (Issue no. 17)
  Chatbot.ipynb
Labels: acwoc, medium

#20 Added the Text-to-Speech support #19 (issue no. 19)
  README.md
Labels: acwoc, easy

#24 Added Annotations feature #23 (Issue no. 23)
  Chatbot.ipynb
Labels: acwoc, medium

#26 Added text translation feature using Google Translate API #25 (Issue no. 25)
  .gitignore
  Chatbot.ipynb
  translator.py
Labels: acwoc, hard

#28 ✨ Enhance PDF Chatbot with major feature improvements and bug fixes #27 (Issue no. 27)
  .env
  .gitignore
  Chatbot.ipynb
  README copy.md
  README.md
Labels: acwoc, hard
